apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: {{ .Release.Name }}
  type: ClusterIP
  ports:
  - name: http
    protocol: TCP
    port: 1521
    targetPort: 1521