env:
- name: ORACLE_PWD
  value: TestM123
- name: ORACLE_SID
  value: FREE
- name: ORACLE_PDB
  value: FREEPDB1
image:
  repository: container-registry-saopaulo.oracle.com/database/free
  tag: 23.3.0.0
secret:
  user: U1lTVEVN
  password: VGVzdE0xMjM=